num_drones: 20
model: iris
initial_positions:
  "1":  { initial_pose: { x: 0 , y: 0 } }
  "2":  { initial_pose: { x: 2 , y: 0 } }
  "3":  { initial_pose: { x: 4 , y: 0 } }
  "4":  { initial_pose: { x: 6 , y: 0 } }
  "5":  { initial_pose: { x: 8 , y: 0 } }
  "6":  { initial_pose: { x: 0 , y: 2 } }
  "7":  { initial_pose: { x: 2 , y: 2 } }
  "8":  { initial_pose: { x: 4 , y: 2 } }
  "9":  { initial_pose: { x: 6 , y: 2 } }
  "10": { initial_pose: { x: 8 , y: 2 } }
  "11": { initial_pose: { x: 0 , y: 4 } }
  "12": { initial_pose: { x: 2 , y: 4 } }
  "13": { initial_pose: { x: 4 , y: 4 } }
  "14": { initial_pose: { x: 6 , y: 4 } }
  "15": { initial_pose: { x: 8 , y: 4 } }
  "16": { initial_pose: { x: 0 , y: 6 } }
  "17": { initial_pose: { x: 2 , y: 6 } }
  "18": { initial_pose: { x: 4 , y: 6 } }
  "19": { initial_pose: { x: 6 , y: 6 } }
  "20": { initial_pose: { x: 8 , y: 6 } }

setpoints:
  "1":
    - [0.0, 0.0, -10.0, 0.0]    # Initial position
    - [0.0, 6.5, -10.0, 0.0]    # Heart top center
    - [0.0, 6.5, -10.0, 1.57]   # Rotate 90°
    - [0.0, 6.5, -10.0, 3.14]   # Rotate 180°
    - [0.0, 6.5, -10.0, 4.71]   # Rotate 270°
    - [0.0, 6.5, -10.0, 0.0]    # Stay at final position
  "2":
    - [2.0, 0.0, -10.0, 0.0]
    - [3.0, 5.0, -10.0, 0.0]    # Right top curve
    - [-5.0, 3.0, -10.0, 1.57]  # Rotate 90°
    - [-3.0, -5.0, -10.0, 3.14] # Rotate 180°
    - [5.0, -3.0, -10.0, 4.71]  # Rotate 270°
    - [5.0, -3.0, -10.0, 0.0]   # Stay at final position
  "3":
    - [4.0, 0.0, -10.0, 0.0]
    - [5.0, 3.0, -10.0, 0.0]    # Right middle
    - [-3.0, 5.0, -10.0, 1.57]  # Rotate 90°
    - [-5.0, -3.0, -10.0, 3.14] # Rotate 180°
    - [3.0, -5.0, -10.0, 4.71]  # Rotate 270°
    - [3.0, -5.0, -10.0, 0.0]   # Stay at final position
  "4":
    - [6.0, 0.0, -10.0, 0.0]
    - [6.0, 1.0, -10.0, 0.0]    # Right side
    - [-1.0, 6.0, -10.0, 1.57]  # Rotate 90°
    - [-6.0, -1.0, -10.0, 3.14] # Rotate 180°
    - [1.0, -6.0, -10.0, 4.71]  # Rotate 270°
    - [1.0, -6.0, -10.0, 0.0]   # Stay at final position
  "5":
    - [8.0, 0.0, -10.0, 0.0]
    - [5.5, -2.0, -10.0, 0.0]   # Right bottom
    - [2.0, 5.5, -10.0, 1.57]   # Rotate 90°
    - [-5.5, 2.0, -10.0, 3.14]  # Rotate 180°
    - [-2.0, -5.5, -10.0, 4.71] # Rotate 270°
    - [-2.0, -5.5, -10.0, 0.0]  # Stay at final position
  "6":
    - [0.0, 2.0, -10.0, 0.0]
    - [4.0, -3.5, -10.0, 0.0]   # Bottom right
    - [3.5, 4.0, -10.0, 1.57]   # Rotate 90°
    - [-4.0, 3.5, -10.0, 3.14]  # Rotate 180°
    - [-3.5, -4.0, -10.0, 4.71] # Rotate 270°
    - [-3.5, -4.0, -10.0, 0.0]  # Stay at final position
  "7":
    - [2.0, 2.0, -10.0, 0.0]
    - [2.0, -4.0, -10.0, 0.0]   # Bottom center
    - [4.0, 2.0, -10.0, 1.57]   # Rotate 90°
    - [-2.0, 4.0, -10.0, 3.14]  # Rotate 180°
    - [-4.0, -2.0, -10.0, 4.71] # Rotate 270°
    - [-4.0, -2.0, -10.0, 0.0]  # Stay at final position
  "8":
    - [4.0, 2.0, -10.0, 0.0]
    - [0.0, -3.5, -10.0, 0.0]   # Bottom left
    - [3.5, 0.0, -10.0, 1.57]   # Rotate 90°
    - [0.0, 3.5, -10.0, 3.14]   # Rotate 180°
    - [-3.5, 0.0, -10.0, 4.71]  # Rotate 270°
    - [-3.5, 0.0, -10.0, 0.0]   # Stay at final position
  "9":
    - [6.0, 2.0, -10.0, 0.0]
    - [-2.0, -4.0, -10.0, 0.0]  # Left bottom
    - [4.0, -2.0, -10.0, 1.57]  # Rotate 90°
    - [2.0, 4.0, -10.0, 3.14]   # Rotate 180°
    - [-4.0, 2.0, -10.0, 4.71]  # Rotate 270°
    - [-4.0, 2.0, -10.0, 0.0]   # Stay at final position
  "10":
    - [8.0, 2.0, -10.0, 0.0]
    - [-4.0, -3.5, -10.0, 0.0]  # Left bottom curve
    - [3.5, -4.0, -10.0, 1.57]  # Rotate 90°
    - [4.0, 3.5, -10.0, 3.14]   # Rotate 180°
    - [-3.5, 4.0, -10.0, 4.71]  # Rotate 270°
    - [-3.5, 4.0, -10.0, 0.0]   # Stay at final position
  "11":
    - [0.0, 4.0, -10.0, 0.0]
    - [-5.5, -2.0, -10.0, 0.0]  # Left bottom
    - [2.0, -5.5, -10.0, 1.57]  # Rotate 90°
    - [5.5, 2.0, -10.0, 3.14]   # Rotate 180°
    - [-2.0, 5.5, -10.0, 4.71]  # Rotate 270°
    - [-2.0, 5.5, -10.0, 0.0]   # Stay at final position
  "12":
    - [2.0, 4.0, -10.0, 0.0]
    - [-6.0, 1.0, -10.0, 0.0]   # Left side
    - [-1.0, -6.0, -10.0, 1.57] # Rotate 90°
    - [6.0, -1.0, -10.0, 3.14]  # Rotate 180°
    - [1.0, 6.0, -10.0, 4.71]   # Rotate 270°
    - [1.0, 6.0, -10.0, 0.0]    # Stay at final position
  "13":
    - [4.0, 4.0, -10.0, 0.0]
    - [-5.0, 3.0, -10.0, 0.0]   # Left middle
    - [-3.0, -5.0, -10.0, 1.57] # Rotate 90°
    - [5.0, -3.0, -10.0, 3.14]  # Rotate 180°
    - [3.0, 5.0, -10.0, 4.71]   # Rotate 270°
    - [3.0, 5.0, -10.0, 0.0]    # Stay at final position
  "14":
    - [6.0, 4.0, -10.0, 0.0]
    - [-3.0, 5.0, -10.0, 0.0]   # Left top curve
    - [-5.0, -3.0, -10.0, 1.57] # Rotate 90°
    - [3.0, -5.0, -10.0, 3.14]  # Rotate 180°
    - [5.0, 3.0, -10.0, 4.71]   # Rotate 270°
    - [5.0, 3.0, -10.0, 0.0]    # Stay at final position
  "15":
    - [8.0, 4.0, -10.0, 0.0]
    - [0.0, 6.5, -10.0, 0.0]    # Top center (shared)
    - [-6.5, 0.0, -10.0, 1.57]  # Rotate 90°
    - [0.0, -6.5, -10.0, 3.14]  # Rotate 180°
    - [6.5, 0.0, -10.0, 4.71]   # Rotate 270°
    - [6.5, 0.0, -10.0, 0.0]    # Stay at final position
  # Inner drones for filled heart
  "16":
    - [0.0, 6.0, -10.0, 0.0]
    - [2.0, 4.0, -10.0, 0.0]    # Inner right
    - [-4.0, 2.0, -10.0, 1.57]  # Rotate 90°
    - [-2.0, -4.0, -10.0, 3.14] # Rotate 180°
    - [4.0, -2.0, -10.0, 4.71]  # Rotate 270°
    - [4.0, -2.0, -10.0, 0.0]   # Stay at final position
  "17":
    - [2.0, 6.0, -10.0, 0.0]
    - [1.0, 3.0, -10.0, 0.0]    # Inner center-right
    - [-3.0, 1.0, -10.0, 1.57]  # Rotate 90°
    - [-1.0, -3.0, -10.0, 3.14] # Rotate 180°
    - [3.0, -1.0, -10.0, 4.71]  # Rotate 270°
    - [3.0, -1.0, -10.0, 0.0]   # Stay at final position
  "18":
    - [4.0, 6.0, -10.0, 0.0]
    - [0.0, 2.0, -10.0, 0.0]    # Inner center
    - [-2.0, 0.0, -10.0, 1.57]  # Rotate 90°
    - [0.0, -2.0, -10.0, 3.14]  # Rotate 180°
    - [2.0, 0.0, -10.0, 4.71]   # Rotate 270°
    - [2.0, 0.0, -10.0, 0.0]    # Stay at final position
  "19":
    - [6.0, 6.0, -10.0, 0.0]
    - [-1.0, 3.0, -10.0, 0.0]   # Inner center-left
    - [-3.0, -1.0, -10.0, 1.57] # Rotate 90°
    - [1.0, -3.0, -10.0, 3.14]  # Rotate 180°
    - [3.0, 1.0, -10.0, 4.71]   # Rotate 270°
    - [3.0, 1.0, -10.0, 0.0]    # Stay at final position
  "20":
    - [8.0, 6.0, -10.0, 0.0]
    - [-2.0, 4.0, -10.0, 0.0]   # Inner left
    - [-4.0, -2.0, -10.0, 1.57] # Rotate 90°
    - [2.0, -4.0, -10.0, 3.14]  # Rotate 180°
    - [4.0, 2.0, -10.0, 4.71]   # Rotate 270°
    - [4.0, 2.0, -10.0, 0.0]    # Stay at final position